// Auto-generated by deployment script
export const CONTRACT_ADDRESS = "0x0555C0c9d8719a800acA5d111239d9c76Ec7A7eF";
export const CHAIN_ID = 5151;
export const RPC_URL = "https://testnet-rpc.mocachain.org";
export const EXPLORER_URL = "https://testnet-scan.mocachain.org";
export const DEPLOYER_ADDRESS = "0x48E8750b87278227b5BBd53cae998e6083910bd9";
export const DEPLOYMENT_TIMESTAMP = 1760629167687;
export { default as ABI } from '@/abi/ProofVerifier.json';
