// Auto-generated by deployment script
export const AUDITOR_REGISTRY_ADDRESS = "0x3933E40028ca7DF666e71Fbb68232be04C499F61";
export const PROOF_VERIFIER_ADDRESS = "0xC988cbc4E9120d8Fd970648F0B93E90c99392ab0";
export const CONTRACT_ADDRESS = "0xC988cbc4E9120d8Fd970648F0B93E90c99392ab0"; // Legacy compatibility
export const ZK_VERIFIER_ADDRESS = "0x0000000000000000000000000000000000000000"; // Placeholder until redeploy
export const CHAIN_ID = 222888; // Standardized to match .env
export const RPC_URL = "https://testnet-rpc.mechain.tech";
export const EXPLORER_URL = "https://testnet-scan.mocachain.org";
export const DEPLOYER_ADDRESS = "0x48E8750b87278227b5BBd53cae998e6083910bd9";
export const DEPLOYMENT_TIMESTAMP = 1761931565698;

// Import ABIs
export { default as AuditorRegistryABI } from '@/abi/AuditorRegistry.json';
export { default as ProofVerifierABI } from '@/abi/ProofVerifier.json';
export { default as ZKVerifierABI } from '@/abi/ZKVerifier.json';
export { default as ABI } from '@/abi/ProofVerifier.json'; // Legacy compatibility
