/**
 * zkVerify — Moca Buildathon 2025 | Auditable Zero-Knowledge Verification Layer
 * 
 * Deployment script for upgraded contracts (AuditorRegistry, ZKVerifier, ProofVerifier).
 * Updates frontend configuration and ABIs after deployment.
 */

const hre = require("hardhat");
const fs = require("fs");
const path = require("path");

async function main() {
  console.log("🚀 Starting upgraded deployment to Moca Chain Testnet...");
  
  const [deployer] = await hre.ethers.getSigners();
  console.log("👤 Deployer address:", deployer.address);
  console.log("💰 Deployer balance:", hre.ethers.formatEther(await hre.ethers.provider.getBalance(deployer.address)), "MOCA");
  
  // Deploy AuditorRegistry first
  console.log("\n📦 Deploying AuditorRegistry...");
  const AuditorRegistry = await hre.ethers.getContractFactory("AuditorRegistry");
  const auditorRegistry = await AuditorRegistry.deploy();
  await auditorRegistry.waitForDeployment();
  const auditorRegistryAddress = await auditorRegistry.getAddress();
  console.log("✅ AuditorRegistry deployed at:", auditorRegistryAddress);
  
  // Deploy ProofVerifier with AuditorRegistry address
  console.log("\n📦 Deploying ZKVerifier...");
  const trustedProver = process.env.TRUSTED_PROVER_ADDRESS || deployer.address;
  const ZKVerifier = await hre.ethers.getContractFactory("ZKVerifier");
  const zkVerifier = await ZKVerifier.deploy(trustedProver);
  await zkVerifier.waitForDeployment();
  const zkVerifierAddress = await zkVerifier.getAddress();
  console.log("✅ ZKVerifier deployed at:", zkVerifierAddress);

  console.log("\n📦 Deploying ProofVerifier...");
  const ProofVerifier = await hre.ethers.getContractFactory("ProofVerifier");
  const proofVerifier = await ProofVerifier.deploy(auditorRegistryAddress, zkVerifierAddress);
  await proofVerifier.waitForDeployment();
  const proofVerifierAddress = await proofVerifier.getAddress();
  console.log("✅ ProofVerifier deployed at:", proofVerifierAddress);
  
  // Set ProofVerifier as authorized caller in AuditorRegistry
  console.log("\n🔗 Linking ProofVerifier to AuditorRegistry...");
  const linkTx = await auditorRegistry.setProofVerifier(proofVerifierAddress);
  await linkTx.wait();
  console.log("✅ ProofVerifier linked to AuditorRegistry");

  console.log("\n🔐 Configuring trusted prover...");
  if ((await zkVerifier.trustedProver()) !== trustedProver) {
    const proverTx = await zkVerifier.setTrustedProver(trustedProver);
    await proverTx.wait();
  }
  console.log(`✅ Trusted prover set to ${trustedProver}`);
  
  // Approve deployer as initial auditor (for testing)
  console.log("\n👨‍💼 Approving deployer as initial auditor...");
  const tx = await auditorRegistry.approveAuditor(deployer.address);
  await tx.wait();
  console.log("✅ Deployer approved as auditor");
  
  // Read ABIs
  const auditorRegistryArtifact = JSON.parse(
    fs.readFileSync(
      path.join(__dirname, "..", "artifacts", "contracts", "AuditorRegistry.sol", "AuditorRegistry.json"),
      "utf8"
    )
  );
  const proofVerifierArtifact = JSON.parse(
    fs.readFileSync(
      path.join(__dirname, "..", "artifacts", "contracts", "ProofVerifier.sol", "ProofVerifier.json"),
      "utf8"
    )
  );
  
  // Ensure frontend directories
  const frontendAbiDir = path.join(__dirname, "..", "frontend", "src", "abi");
  const frontendConfigDir = path.join(__dirname, "..", "frontend", "src");
  
  if (!fs.existsSync(frontendAbiDir)) fs.mkdirSync(frontendAbiDir, { recursive: true });
  if (!fs.existsSync(frontendConfigDir)) fs.mkdirSync(frontendConfigDir, { recursive: true });
  
  // Write ABIs
  fs.writeFileSync(
    path.join(frontendAbiDir, "AuditorRegistry.json"),
    JSON.stringify(auditorRegistryArtifact.abi, null, 2)
  );
  fs.writeFileSync(
    path.join(frontendAbiDir, "ProofVerifier.json"),
    JSON.stringify(proofVerifierArtifact.abi, null, 2)
  );

  const zkVerifierArtifact = JSON.parse(
    fs.readFileSync(
      path.join(__dirname, "..", "artifacts", "contracts", "ZKVerifier.sol", "ZKVerifier.json"),
      "utf8"
    )
  );

  fs.writeFileSync(
    path.join(frontendAbiDir, "ZKVerifier.json"),
    JSON.stringify(zkVerifierArtifact.abi, null, 2)
  );
  
  // Create config file
  const configContent = `// Auto-generated by deployment script
export const AUDITOR_REGISTRY_ADDRESS = "${auditorRegistryAddress}";
export const PROOF_VERIFIER_ADDRESS = "${proofVerifierAddress}";
export const CONTRACT_ADDRESS = "${proofVerifierAddress}"; // Legacy compatibility
export const ZK_VERIFIER_ADDRESS = "${zkVerifierAddress}";
export const CHAIN_ID = 222888; // Standardized to match .env
export const RPC_URL = "https://testnet-rpc.mechain.tech";
export const EXPLORER_URL = "https://testnet-scan.mocachain.org";
export const DEPLOYER_ADDRESS = "${deployer.address}";
export const DEPLOYMENT_TIMESTAMP = ${Date.now()};

// Import ABIs
export { default as AuditorRegistryABI } from '@/abi/AuditorRegistry.json';
export { default as ProofVerifierABI } from '@/abi/ProofVerifier.json';
export { default as ZKVerifierABI } from '@/abi/ZKVerifier.json';
export { default as ABI } from '@/abi/ProofVerifier.json'; // Legacy compatibility
`;
  
  fs.writeFileSync(path.join(frontendConfigDir, "config.js"), configContent);
  console.log("\n📝 Frontend config updated");
  
  // Create deployment info
  const deploymentInfo = {
    auditorRegistry: auditorRegistryAddress,
    proofVerifier: proofVerifierAddress,
    zkVerifier: zkVerifierAddress,
    trustedProver,
    deployer: deployer.address,
    chainId: 222888,
    network: "moca-testnet",
    timestamp: new Date().toISOString(),
    blockNumber: await hre.ethers.provider.getBlockNumber(),
  };
  
  fs.writeFileSync(
    path.join(__dirname, "..", "deployment-info.json"),
    JSON.stringify(deploymentInfo, null, 2)
  );
  
  // Update .env file
  const envPath = path.join(__dirname, "..", ".env");
  let envContent = fs.existsSync(envPath) ? fs.readFileSync(envPath, "utf8") : "";
  
  // Update or add contract addresses
  if (envContent.includes("NEXT_PUBLIC_AUDITOR_REGISTRY_ADDRESS")) {
    envContent = envContent.replace(
      /NEXT_PUBLIC_AUDITOR_REGISTRY_ADDRESS=.*/,
      `NEXT_PUBLIC_AUDITOR_REGISTRY_ADDRESS=${auditorRegistryAddress}`
    );
  } else {
    envContent += `\nNEXT_PUBLIC_AUDITOR_REGISTRY_ADDRESS=${auditorRegistryAddress}`;
  }
  
  if (envContent.includes("NEXT_PUBLIC_CONTRACT_ADDRESS")) {
    envContent = envContent.replace(
      /NEXT_PUBLIC_CONTRACT_ADDRESS=.*/,
      `NEXT_PUBLIC_CONTRACT_ADDRESS=${proofVerifierAddress}`
    );
  } else {
    envContent += `\nNEXT_PUBLIC_CONTRACT_ADDRESS=${proofVerifierAddress}`;
  }

  if (envContent.includes("NEXT_PUBLIC_ZK_VERIFIER_ADDRESS")) {
    envContent = envContent.replace(
      /NEXT_PUBLIC_ZK_VERIFIER_ADDRESS=.*/,
      `NEXT_PUBLIC_ZK_VERIFIER_ADDRESS=${zkVerifierAddress}`
    );
  } else {
    envContent += `\nNEXT_PUBLIC_ZK_VERIFIER_ADDRESS=${zkVerifierAddress}`;
  }
  
  fs.writeFileSync(envPath, envContent);
  
  console.log("\n📊 Deployment Summary:");
  console.log("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
  console.log(`AuditorRegistry: ${auditorRegistryAddress}`);
  console.log(`ProofVerifier:   ${proofVerifierAddress}`);
  console.log(`ZKVerifier:      ${zkVerifierAddress}`);
  console.log(`Trusted Prover:  ${trustedProver}`);
  console.log(`Deployer:        ${deployer.address}`);
  console.log(`Network:         Moca Chain Testnet (222888)`);
  console.log("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
  
  console.log("\n🔗 Explorer Links:");
  console.log(`AuditorRegistry: https://testnet-scan.mocachain.org/address/${auditorRegistryAddress}`);
  console.log(`ProofVerifier:   https://testnet-scan.mocachain.org/address/${proofVerifierAddress}`);
  console.log(`ZKVerifier:      https://testnet-scan.mocachain.org/address/${zkVerifierAddress}`);
  
  console.log("\n🎉 Deployment completed successfully!");
  console.log("\n📋 Next Steps:");
  console.log("1. Verify contracts on explorer");
  console.log("2. Approve additional auditors using admin dashboard");
  console.log("3. Update backend .env with contract addresses");
  console.log("4. Deploy frontend and backend");
  console.log("5. Set up reputation fetching cron job");
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error("❌ Deployment failed:", error);
    process.exit(1);
  });
